### ISSUE TITLE
Looting corpse still possible

### ISSUE THREAD

**Issue by Pojus** [TAWTonic/Altis-Life#343]
If you spam the key for inventory " i " and trying to loot with mouse wheel (clicking it or using spacebar on inventory) you are able to access to the corpse inventory and completely loot it bypassing the check for no looting added some patches ago.

**Comment by ColinM9991** [comment]
Yet another static key press ^

For the love of god people, use the action key names...

if((_code in (actionKeys "Inventory"))&&(!(isNull (findDisplay 602)) && (isPlayer cursorTarget OR vehicle cursorTarget != cursorTarget OR alive cursorTarget))) {
	closeDialog 0; closeDialog 0;
}
