### ISSUE TITLE
Linux Core configuration quadbike garage retrieve price bug

### ISSUE THREAD

**Issue by KeanePW** [TAWTonic/Altis-Life#355]
Linux

https://github.com/TAWTonic/Altis-Life/blob/master/extDB-Build/Altis_Life.Altis/core/configuration.sqf

Line 322

B_QuadBike_01_F => B_Quadbike_01_F

**Comment by ColinM9991** [comment]
Go in game and spawn a quadbike.

veh = "B_QuAdBiKe_01_f" createVehicle position player;

**Comment by KeanePW** [comment]
This is on Linux where case sensitivity matters. The script might work on windows but I don't. Moreover you miss the point, the issue is with price being wrong. You seem to think that he issue is with spawning a vehicle. Please test before posting. Thanks.

**Comment by KeanePW** [comment]
Updated.

**Comment by Itsyuka** [comment]
Interdasting, I'll leave this to Tonic since he still hasn't thrown me the latest files
