### ISSUE TITLE
Server not sending UID to Navicat Database

### ISSUE THREAD

**Issue by GetSomePanda** [TAWTonic/Altis-Life#364]
When I try join my server it says the sever has no information about my uid and then trys to connect to my uid it stays like this and does not allow me to get on my server, It seems to be something in my extDB as its filled up my logs with it, so here is what i got in the extDB logs 

http://pastebin.com/im1iuv2j

Not sure what the problem is, I am using Navicat and mysql obv but I have not figured this out yet
Hopefully one of you guys could help be as it would grately be appreciated!

**Comment by Itsyuka** [comment]
Post this on the forums.
