### ISSUE TITLE
Textures from cars

### ISSUE THREAD

**Issue by deathlyend** [TAWTonic/Altis-Life#374]
hi everyone,

i have a paa file that i wanna do as a texture in my server but when i add the line in the fn_vehiclecolorcfg and the str they dont apear in the game menu how to fix this

![arma 3 color cfg](https://cloud.githubusercontent.com/assets/11195603/6419194/8372700c-bebb-11e4-94d4-20f8d4a3bfb1.png)
![arma 3 color str](https://cloud.githubusercontent.com/assets/11195603/6419195/8372cf2a-bebb-11e4-9f0e-4e1fac7deb3e.png)

whats really strange is that there is a police color but its not the one i put into and it was already there before i made police
pls help me 

kind regards.
deathlyend

**Comment by ColinM9991** [comment]
For fuck sake, this is for issues relating to Altis Life as a whole; not your own personal issues.

**Comment by deathlyend** [comment]
iam sorry but i thought this was an issue to 4.0 becaus i see other servers and things that have it and they use the 3.4.8 orso that why i thought it was a 4.0 version issue
