### ISSUE TITLE
New update doesn't work with exdb2

### ISSUE THREAD

**Issue by Ghostaunt** [TAWTonic/Altis-Life#384]
I tried the new update live server with extdb2 v63 and v66 but both doesn't work.
Someone get the same issue ?

14:03:45 "extDB2: Error with Database Connection"

Before this update, with extdb v35 everything worked
Thanks

**Comment by TAWTonic** [comment]
I have no problems with it, I run the latest extDB2 version, The issue you might of had is that the database was named Database2 (in life_server) and not AltisLife like the version itsyuka had before he raged.

**Comment by Ghostaunt** [comment]
I tried multiple version of EXTDB2 and none  work :/
"22:12:00 "extDB2: Error with Database Connection"

Here my extdb part of mysql database

[AltisLife]
Type = MySQL
Name = arma3life

Username = root
Password = 
IP = 127.0.0.1
Port = 3306

minSessions = 1
;maxSessions = 4
idleTime = 60

compress = false
; Should only use this if MySQL server is external. Also only for MySQL

Secure Auth = true
; Recommend you turn this on

**Comment by miragecentury** [comment]
Can you see in extDb log dir if you see more information ?

**Comment by Ghostaunt** [comment]
No log created in extdb

**Comment by miragecentury** [comment]
add this to your extdb config 
```
[Log]
;; Flush Logs after each write, more work on Harddrive
Flush = true
```

**Comment by Ghostaunt** [comment]
Ok i added this line, started again my server, but no more logs :/

here full ini
-------

[Main]
Version = 5

;Threads = 0  
; Default Value is the number of CPU Cores Detected (max value is 6, min value is 2)
; Linux Chroot Environment might only Detect 1 CPU Cores i.e bind /proc

Randomize Config File = false
;This is a legacy option to randomize config file for Arma2 Servers.


[Rcon]
;; This is functional, should be working fine. Just needs abit of testing on a live Server

Port = 2302
Password = password


[Steam]
;; This is for VAC Protocol for VAC Bans + Steam Friends.
;; This currently has a bug in it, will be fixed next version.
;; Think of it as tech preview option.
;; https://steamcommunity.com/dev/apikey
API Key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


[VAC]
;; This feature requires Steam + Rcon to be enabled.
;; Also this feature is called via SQF Code atm, i.e it doesn't auto detect players joining server yet....

Auto Ban = false

;; For Player to get banned ( their total VAC Bans => NumberOfVACBans)  AND ( Days Since their Last Ban was <= DaysSinceLastBan)
;; This is also used extDB Protocol VAC:VACBanned returned results
NumberOfVACBans = 1
DaysSinceLastBan = 999999999

BanDuration = 0
;; 0 = Forever, otherwise its x Minutes
BanMessage = Steam VAC Banned


[Log]
;; This is just config options for Rcon Logging + BE Logging
;;		Has no effect on extDB Logging
Mode = sync
;; sync / async
;;	ASync is just kinder on your Harddrive, may be lose of data in the event of a crash.
;; Flush Logs after each write, more work on Harddrive
Flush = truew²w


[AltisLife]
;; 	AtlisLifeRPG uses Database2 by default
Type = MySQL
;; Name = arma3life4_opti
Name = arma3life

Username = root
Password = 
IP = 127.0.0.1
Port = 3306

minSessions = 1
;maxSessions = 4
idleTime = 60

compress = false
; Should only use this if MySQL server is external. Also only for MySQL

Secure Auth = true
; Recommend you turn this on

**Comment by Ghostaunt** [comment]
"Oups mistake with paste"
It's Flush = true ;)

**Comment by miragecentury** [comment]
Can you try with a password ?

**Comment by Ghostaunt** [comment]
Ok, tested with a password and no change

**Comment by Itsyuka** [comment]
Apparently you guys need to read.

**Comment by Ghostaunt** [comment]
"Apparently you guys need to read."

You too... Cause the problem is not solved.

**Comment by Itsyuka** [comment]
"I have no problems with it, I run the latest extDB2 version, The issue you might of had is that the database was named Database2 (in life_server) and not AltisLife like the version itsyuka had before he raged."

Interdasting, we both can't be right. Also Killerty69 said, "i tested it myself".

**Comment by Ghostaunt** [comment]
I think nobody realy tested it

**Comment by TAWTonic** [comment]
Really? Nobody tested it? Then why am I using this very same build right now with extDB 66? Maybe I'm smoking.

**Comment by Ghostaunt** [comment]
I found the issue. 
I used a different folder name for extdb2 as extdb and I renamed my extdb2.dll to extdb.dll...
When I started my server I used "-mod=@life_server;@extDB" and it doesn't worked

Now I tested it with an extDB2 folder and it work.
Don't know if it's my eror or not. But solved.

Thanks anyway for your help, you are not smoking.

**Comment by danielstuart14** [comment]
Linux? I think arma server is bugged on linux. It isn't loading the addons... (sometimes it does, sometimes it doesn't...) I manage to fix it, you just need to copy extDB files to arma's root folder, and life_server.pbo to arma's addons folder. It'll force arma to load your mods.
 It got me three days before I figure out. And it was exactly as your situation, no logs, nothing...

**Comment by Itsyuka** [comment]
Linux is strange indeed, full paths, that's why it was suggested to use full paths ("/path/to/arma3/@extDB2;") instead of "@extDB2;".
