### ISSUE TITLE
Vehicle not saving on database

### ISSUE THREAD

**Issue by danielstuart14** [TAWTonic/Altis-Life#390]
After https://github.com/TAWTonic/Altis-Life/commit/a0ce6df0bf1b26d670681e8a03ce5ead5b23faac vehicles aren't saving on database... It makes impossible to store cars on garage..

**Comment by ColinM9991** [comment]
Logs.

On 15 November 2015 at 03:59, Daniel Stuart <notifications@github.com>
wrote:

> After a0ce6df
> <https://github.com/TAWTonic/Altis-Life/commit/a0ce6df0bf1b26d670681e8a03ce5ead5b23faac>
> vehicles aren't saving on database... It makes impossible to store cars on
> garage..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TAWTonic/Altis-Life/issues/390>.
>



-- 
Sincerely,

Colin

**Comment by danielstuart14** [comment]
Here they're https://gist.github.com/danielstuart14/ba9de4f840c0031b2fb0
I can't found anything on they..

**Comment by Itsyuka** [comment]
https://github.com/TAWTonic/Altis-Life/commit/26cc19d51ac7e27cee161d2964f8d238f25e70b0
