### ISSUE TITLE
Abort Button Fix

### ISSUE THREAD

**Issue by GetSomePanda** [TAWTonic/Altis-Life#391]
The abort button is enabled when its counting down, basically whilst its counting down its clickable.

Heres the fix:

Just in the fn_escInterupt in the waitUntil statement add _abortButton ctrlEnable false;

Then after the waitUntil is done add _abortButton ctrlEnable true;

Pretty easy fix but just letting ye guys know same with others having problems.

**Comment by Itsyuka** [comment]
https://github.com/TAWTonic/Altis-Life/commit/82b96c67c42718e8cbe6287997cc871040f51b2a
