### ISSUE TITLE
Initial money stuck on $2500

### ISSUE THREAD

**Issue by danielstuart14** [TAWTonic/Altis-Life#392]
Somehow new players can't get the amount of money set on configuration.sqf...
They only get $2500, doesn't matter how much is set to.
Nothing on rpt logs...

**Comment by ColinM9991** [comment]
This isn't an Altis life bug

**Comment by danielstuart14** [comment]
it seems to be since it's happening with stock build from here.

**Comment by danielstuart14** [comment]
My workaround by now is changing default BANK value on fn_insertRequest.sqf

**Comment by houston08** [comment]
Colin is correct. You've changed something somewhere that caused the issue. Go through everything you've changed since stock or start over and port your changes.
