### ISSUE TITLE
Tazed players are invisible

### ISSUE THREAD

**Issue by danielstuart14** [TAWTonic/Altis-Life#393]
When a cop tazes a player, player gets invisible until tazer animation stops.

**Comment by danielstuart14** [comment]
Also knockedOut isn't working.

**Comment by SPS6** [comment]
[This post](http://www.altisliferpg.com/topic/9210-40-tazing-makes-you-invisible/?hl=invisible) suggests commenting out the following two lines.

```
_obj = "Land_ClutterCutter_small_F" createVehicleLocal ASLTOATL(visiblePositionASL player); //Again why in the fuck was this being created globally? I could of                         sworn I made it local back in ARMA 3 Beta...
_obj setPosATL ASLTOATL(visiblePositionASL player);
```

Is this a suitable workaround to use? or is there a recommended fix for this?

Also the same is true for when players are knocked out.

**Comment by danielstuart14** [comment]
I managed to get this working without commenting anything...
We just need to set the object as global, so, other users can see it.
Here it is: https://github.com/danielstuart14/Altis-Life/commit/41b0243ecfae0a7f4eee90520da883f5eacfca7a
