### ISSUE TITLE
Vehicular skins for respawned players

### ISSUE THREAD

**Issue by danielstuart14** [TAWTonic/Altis-Life#394]
Players which had respawn can't see vehicles skins from vehicles that already were on map before respawn.

**Comment by Heavybob** [comment]
fn_vehicleShopBuy 

I had an idea to just recall the assign color command command the same way it works for when you buy or retrieve a veh.

Ref like 63 and 73 of fn_VehicleShopBuy.sqf

**Comment by danielstuart14** [comment]
No need, already found an way... Will just test it.
