### ISSUE TITLE
Infinte money glitch.

### ISSUE THREAD

**Issue by MrMomox** [TAWTonic/Altis-Life#395]
Hello,
there´s a simple money glitch:
1. Buy nv-googles (or sth. else, nv-googles are the best, because they are expensive)
2. Remove everything except you nv-googles and a tshirt from your inventroy
3. Put the nv-googles in you tshirt
4. Sell the nv-googles, they won't disappear so you can use an auto clicker...

Have you got a fix for this (it works with every item).
i don´t want to disable the "sell" button :/
(I am using the newest version of altis life on linux)
Thank you!

**Comment by Heavybob** [comment]
Disable the sell button. :)

**Comment by MrMomox** [comment]
Please read the whole text, not just the title...

**Comment by Heavybob** [comment]
I saw this, another way is to just set the price for selling to zero til its fixed.

**Comment by Jawshy** [comment]
This is no longer an issue. It was fixed I think in [Altis-Life v4.0.2 Preview Build](https://github.com/TAWTonic/Altis-Life/releases/tag/v4.0.2-preview).
