### ISSUE TITLE
Cop Vehicle Interaction 4.0.2 preview

### ISSUE THREAD

**Issue by Angrygargamel** [TAWTonic/Altis-Life#401]
registration and search vehicle is not working...
registration is just doing nothing at all and search vehicle doesnt find any illegal items like heroin which should definitely be marked as illegal...

**Comment by danielstuart14** [comment]
These commits should fix:
https://github.com/danielstuart14/Altis-Life/commit/e49633b5df41ce84a8592b46de8bcfb0efbd15b3
https://github.com/danielstuart14/Altis-Life/commit/f794bc21d3d43da473da0cc27bb7025cd91c8770
