### ISSUE TITLE
Cop Player Interaction 4.0.2 preview

### ISSUE THREAD

**Issue by Angrygargamel** [TAWTonic/Altis-Life#402]
what is working:
escort player / stop escort
send to jail

what is partially working:
put in vehicle - you can put him in the vehicle but the can change seats and also exit the vehicle even when restrained

what is not working:
check licenses - no reaction
search player - just shows the hint SEARCHING... and then the whole menu doesnt work anymore
ticket player - doesnt open the ticket menu

**Comment by Itsyuka** [comment]
Oh Tonic, change the effected functions that are using remoteExecCall to remoteExec.

**Comment by Angrygargamel** [comment]
simple as that? really?
because i tried it on player search... no success yet... maybe i missed a line or two...

**Comment by danielstuart14** [comment]
@Angrygargamel just player search isn't working changing remoteExecCall to remoteExec?

**Comment by Angrygargamel** [comment]
check licenses isnt working...
ticket player isnt working
and search player isnt working...
i tried to change it from remoteexeccall to remoteexec... didnt help
so i changed in the regarding files too... but still no success...

**Comment by ALRMatty** [comment]
Itsyuka are you able to fix this issue? :)

**Comment by AlphaKingd** [comment]
Would be awsome :)

**Comment by SPS6** [comment]
^ +1

**Comment by Angrygargamel** [comment]
you guys should start reporting the rest of the bugs too...
there are many other things which arent working correctly...
if you are restrained and put in a car you can switch seats... and exit the vehicle for example

**Comment by ALRMatty** [comment]
Yep, I agree. But in saying that key functions of the roles need to be functional. Police not being able to search players, check licenses or even ticket them is a pretty serious issue.

Switching seats restrained and or exiting can be mitigated with RP rules, for now, but you're right it needs fixing... I wish I did post my bugfixes that ive already made because I have done a few. Just can't get my head around this cop interaction issue :/ HELP US ITSYUKA WE NEED YOU <3

**Comment by SPS6** [comment]
ok well I have fixed checking licences:

In **CfgRemoteExec.hpp**

```
F(life_fnc_licenseRead,CLIENT)
```

is misspelt and should say license**_s_**, just change it to:

```
F(life_fnc_licensesRead,CLIENT)
```

**Comment by Ethan097** [comment]
Okay thanks heaps SPS6, i'll let you know if i fix the ticketing :)

**Comment by Ethan097** [comment]
Have you fixed Check Registration on vehicles?

**Comment by SPS6** [comment]
> Itsyuka commented 12 days ago
> Oh Tonic, change the affected functions that are using remoteExecCall to remoteExec.

@Itsyuka If this is what you are saying will fix this, is there any change that you might be able to post a commit, or even a comment on here, advising of a fix for cops searching vehicles/players, checking owners of vheicles and issuing tickets please?

**Comment by Gregory017** [comment]
That would be great to have news soon... Still looking for an issue... Thanks!

**Comment by AlphaKingd** [comment]
Can anybody fix it

**Comment by CrazyFluff** [comment]
script marcos not parasing the information properly on fn_searchClient and fn_copSearch is a really pain in the ass but i got it to work so its w/e
