### ISSUE TITLE
Joining and leaving Gang Bug.

### ISSUE THREAD

**Issue by Heavybob** [TAWTonic/Altis-Life#406]
If you join a gang and then leave the gang, it does not change any serverside entry in the database preventing being able to leave the group.

**Comment by manzarek123** [comment]
It is because the player leave the group before the server try to get the group ID
When last player leave a group the group is deleted then the server cannot get the group id with getVariable on a non existing group.
You have to pass the player object to the updategang function and leave the group once you deleted the gang in the db.

@TAWTonic

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/b56a987dd2a54c9fb3d076642b25ecb7d21e5a9a
Thx to @Provokan

**Comment by sargken** [comment]
@danielstuart14 is your fork updated with fixes? Mind in i fork yours if is so.

**Comment by danielstuart14** [comment]
Are you talking about the commit itself or the whole repo?
Commit: I did some changes to match new remoteExec method & added the new variable to spyglass.
Repo: I'm working on top of latest tonic commit, but with my own commits. A new fork of altis.

**Comment by sargken** [comment]
Yeah the repo considering there is alot of bugs in the master branch.

**Comment by danielstuart14** [comment]
yes, I'm without an windows machine right now, so I can't test it (Arma 3 builds for mac are crap and outdated), but I'm working on fix for all the bugs. Will get an windows machine to test everything, something I need logs and client to test before pushing.

**Comment by sargken** [comment]
I can teat tomarrow or wensday sometime. 1 ? Is the new builds and since when has it been using extdb 2?

**Comment by sargken** [comment]
Disregard my last comment, but i can test tomarrow or Wednesday. Im on my phone so sorry for bad spelling.

**Comment by danielstuart14** [comment]
No problem. What is giving a pain in the ass is the Cop Interaction menu.
I would need to someone test it and send me Client and Server RPT logs after testing. 
I can't fix it without logs.

Just take your time
