### ISSUE TITLE
Backpacks weight stacking

### ISSUE THREAD

**Issue by AveUrsus** [TAWTonic/Altis-Life#408]
When a player is using closing shop backpack weight is increasing - for example try select 2 or 3 backpacks and buy one of them - total  max weight will be like HEMTT trunk size.

**Comment by mur202** [comment]
*Clothing shop* and yes this isnt working

**Comment by danielstuart14** [comment]
https://github.com/danielstuart14/Altis-Life/commit/679d690792795d0e8a5756c12615a7348d49c881
