### ISSUE TITLE
Wantedlist & Starting money doesn't work

### ISSUE THREAD

**Issue by Felix2** [TAWTonic/Altis-Life#409]
Whenever somebody kills a cop or civilian they don't end up in the wanted list.

When setting the startup money it doesn't change. You get only 2,500$. This for the newest version.

**Comment by Felix2** [comment]
The Startup money has been solved, however the Wantedlist is still not working properly.

**Comment by danielstuart14** [comment]
Just killing isn't showing up on Wanted list? Or any other crime?
Also, can you do some stuff for me?
Check if killer firearm license is being removed & attach here Client and Server RPT logs of the session where you got killed (by someone).

**Comment by sargken** [comment]
I will look into starting money if u want to look into wanted lists tomarrow

**Comment by danielstuart14** [comment]
Here's the fix for starting money: https://github.com/danielstuart14/Altis-Life/commit/cc2e0a3e07c33b7019d188b2a9f923a3914b1a75

**Comment by mur202** [comment]
@danielstuart14 Just tried the wanted list and it doesnt seem to work. They get added to the wanted list but they wont show up. This is for every crime, It says that there is no one wanted

**Comment by eoinkealey** [comment]
hows it going ladds we just got our 4.0 server up and running again i'm not much of a coder but we could use some help from the people who are. i'm having the same issue with the wanted list as felix it says that the civs are being added to the list but are not being displayed if anyone knows of or had the same issue pls let me know  im at a loss help ?

**Comment by BarboneDiLusso** [comment]
same problem :(
