### ISSUE TITLE
Sorry, You don't have permission for that!

### ISSUE THREAD

**Issue by KillianDolan** [TAWTonic/Altis-Life#410]
This error display's to me when I try look at the website.
![capture](https://cloud.githubusercontent.com/assets/16307367/11814070/c96f82aa-a33c-11e5-9f26-960c142414f6.PNG)
If I am banned, witch now I presume I am I'd like to know the reason why.

Regards,
Killian Dolan

**Comment by snajdan** [comment]
why the hell you asking for that at github?

**Comment by KillianDolan** [comment]
Because on altos life RPGs site when you click on support it redirects you here, I'd appreciate if you didn't show an attitude.

**Comment by KillianDolan** [comment]
Sorry it's issue tracker not support.

**Comment by KillianDolan** [comment]
Ridiculous that you don't help your member's.
-Rep on Altis Life RPG

**Comment by danielstuart14** [comment]
Github is for the mod development, not for any forum issue.
I'm sorry, but we can't help you here. And even if I want, I'm not mod or anything on forum.
So stop making noise, @snajdan already said that.
