### ISSUE TITLE
Cop Restaining

### ISSUE THREAD

**Issue by CrazyFluff** [TAWTonic/Altis-Life#413]
Have a bug were a cop will restrain you and it goes through the animation but the user/civ can just get up and walk around like it didnt happen

**Comment by danielstuart14** [comment]
As anyone is updating this repo anymore, here is the fix: https://github.com/danielstuart14/Altis-Life/commit/681456f5ba51eaddadd1894cd384bb620d9129e2

And here's my repo: https://github.com/danielstuart14/Altis-Life
