### ISSUE TITLE
 Knock down problem

### ISSUE THREAD

**Issue by crackhead** [TAWTonic/Altis-Life#423]
We are currently testing the current 4.1 here we noticed the following problems :

if one  Knock down a person we get the error error General error in the expressive core / functions / fn_keyhandler.sqf line 106

**Comment by Heavybob** [comment]
Confirmed, issue exists.

**Comment by NiiRoZz** [comment]
You can explicit more please, exactly Log.

Cordially NiiRoZz.

**Comment by Jawshy** [comment]
This is no longer an issue. It was fixed in [v4.3 release! Stable version](https://github.com/TAWTonic/Altis-Life/releases/tag/v4.3).

**Comment by Heavybob** [comment]
Issue was resolved a few weeks ago. This repo is outdated. 
https://github.com/ArmaLife/Altis
