### ISSUE TITLE
No config option found

### ISSUE THREAD

**Issue by killie01** [TAWTonic/Altis-Life#425]
Although i've seen this error multiple times on forums, this one confuses me.

extDB2: Found extdb-conf.ini
extDB2: Detected 32 Cores, Setting up 6 Worker Threads

[13:32:24:908471 +00:-1] [Thread 5796] extDB2: No Config Option Found: 

It doesnt say what it's trying to find...
My config.cpp does have AltisLife as DatabaseName

**Comment by killie01** [comment]
Debug:

[14:45:41:461982 +00:-1] [Thread 5436] extDB2: Input from Server: 9:ADD_DATABASE:
[14:45:41:461982 +00:-1] [Thread 5436] extDB2: No Config Option Found:

**Comment by killie01** [comment]
Fixed this.

**Comment by clackd1amond** [comment]
How did you fix this?

**Comment by killie01** [comment]
Sorry, but i don't even remember.
My mistake for not documenting a fix.
It might have been a file permissions error, i don't know...
