### ISSUE TITLE
license has weird a in front of it 

### ISSUE THREAD

**Issue by numpty9989** [TAWTonic/Altis-Life#428]
this is a gyazo off it (no errors in RPT No changes ti prices) https://gyazo.com/7bcb285e11ac264e51d7ff5f2d7246bc

**Comment by danielstuart14** [comment]
Did you change something? In english it should be $ instead £

**Comment by tkcjesse** [comment]
Can you post your RPT log please. You may have missed something.

**Comment by numpty9989** [comment]
clientside http://pastebin.com/PWquPJ70 Serverside http://pastebin.com/ugF9JG3x

**Comment by numpty9989** [comment]
OMFG it was my map dev :( he added it by accident nvm

**Comment by tkcjesse** [comment]
Just  close this then.

**Comment by numpty9989** [comment]
ok cheers

**Comment by KiritoKirigaya2601** [comment]
Also, we are a UK server not US, which is why we had £

**Comment by danielstuart14** [comment]
Yeah,  I know... Just said because probably it was changed, and it should be the root of problem.

**Comment by numpty9989** [comment]
no the £ is not the problem ti was added my accident fom map dev its fixed now

**Comment by KiritoKirigaya2601** [comment]
"Did you change something? In english it should be $ instead £" - Nice :)

English = Pounds
American = Dollars

I'm sorry if i'm rude, but wtf xD

**Comment by danielstuart14** [comment]
Yeah, that is what I was trying to say... Going to add an option for changing the money simbol in config master

**Comment by danielstuart14** [comment]
English strings in-game = we use dollar

**Comment by numpty9989** [comment]
adding a string would be extremly helpful mate as changing $ to £ in 200+ files is time consuming

**Comment by KiritoKirigaya2601** [comment]
Awesome Daniel
