### ISSUE TITLE
Error on Weapon Shop Action

### ISSUE THREAD

**Issue by Locxion** [TAWTonic/Altis-Life#430]
When i try to open The Civ Gunshop or the Rebel Gunshop i get a Error:

Client .rpt
21:05:14 Error in expression <mList)-1,_itemInfo select 2];
_itemList lbSetValue[(lbSize _itemList)-1,(_x sele>
21:05:14   Error position: <lbSetValue[(lbSize _itemList)-1,(_x sele>
21:05:14   Error Type Any, expected Number
21:05:14 File mpmissions\__CUR_MP.Altis\core\shops\fn_weaponShopFilter.sqf, line 29

**Comment by sargken** [comment]
Did you edit the gunshop files?

**Comment by Locxion** [comment]
you mean Config_Weapons.hpp ? yes i did

**Comment by sargken** [comment]
You have a syntax error in there then.

**Comment by sargken** [comment]
Look for missing , or "

**Comment by Locxion** [comment]
yeah thats it ... two pairs of " missing!
Thanks a lot!
Can i ask you something else?
Shift + H doesnt work to holster Weapon.
didnt modify anything else ...

**Comment by sargken** [comment]
https://github.com/ArmaLife/Altis post issues here now its the new build page for altis life.

**Comment by Locxion** [comment]
maybe i should pull the files from this git? maybe its fixed then?

**Comment by sargken** [comment]
I would this new git has alot of features added in look at the release tab.

**Comment by danielstuart14** [comment]
Here I'll push just final releases. 
Like v4.3(final release)

Currently we are in 4.3.3 in ArmaLife Repo. When it get stable, it'll be 4.3

**Comment by sargken** [comment]
@heavybob can explain some of these features better than i can.

**Comment by Locxion** [comment]
i try the files from https://github.com/ArmaLife/Altis out if is anything wrong i can backroll later ... if something wrong i will tell you in the other repo.
Thanks anyway :D
