### ISSUE TITLE
3DEN Editor Update ¦ Altis Life doesn't load.

### ISSUE THREAD

**Issue by 5RBJS** [TAWTonic/Altis-Life#435]
Since the 3DEN update for arma 3, Altis Life will not load on my server. The link below is a link to see the screenshot of the error.

**Comment by 5RBJS** [comment]
Sorry, wrong link. Here's the new image:

[http://imgur.com/2DC8dbJ](url)

**Comment by harmdhast** [comment]
This is not an altis life error.
Please post logs.

**Comment by 5RBJS** [comment]
It is an Altis life error as the people who host my server said there is something wrong with Altis life after the update. They said contact them or wait for the next update. The error I've got is in the picture above.

**Comment by 5RBJS** [comment]
The errors that are found in the screenshot are only occurring when I load Altis life, and it even says 'loading Altis life'. 

Maybe I didn't explain what is happening well enough.

When I put Altis life on the server it comes up with these errors in the console.

In-game, it keeps saying in the text box (bottom left multiplayer bit) "error loading mission". It repeatedly says this and keeps restarting the mission by itself. I don't get any further than the lobby.

**Comment by danielstuart14** [comment]
just load the mission with 3DEN , and then, save it. Should fix.

**Comment by danielstuart14** [comment]
v4.4r1 already solves that.
Here: https://github.com/ArmaLife/Altis (This isn't even released yet, so, you souldn't use it in your server)

**Comment by danielstuart14** [comment]
v4.4r1 already solves that.
Here: https://github.com/ArmaLife/Altis (This isn't even released yet, so, you souldn't use it in your server)

**Comment by 5RBJS** [comment]
Ok. Also I have already launched it in Eden and saved it but that didn't seem to do the job. I'll give it one more try :)

**Comment by br1zey** [comment]
same Problem Error Loeading Mission then i use a 2D Editor  map is woking then i loeading in 3D and save its cant loading :(

**Comment by Denwo22** [comment]
i updatet my mission.sqm, all makers not compatible with eden. and now i update it bit to bit.
kavala is fix and my mates check soon other points to fix it.

mission.sqm
[Uploading mission.txt…]()

edit:
Altis_Life.Altis/dialog/function/fn_spawnPointCfg.sqf

/*
	File: fn_spawnPointCfg.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master configuration for available spawn points depending on the units side.
	
	Return:
	[Spawn Marker,Spawn Name,Image Path]
*/
private["_side","_return"];
_side = [_this,0,civilian,[civilian]] call BIS_fnc_param;

//Spawn Marker, Spawn Name, PathToImage
switch (_side) do
{
	case west:
	{
		_return = [
			["cop_spawn_2","Kavala HQ","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["cop_spawn_3","Pyrgos HQ","\a3\ui_f\data\map\MapControl\fuelstation_ca.paa"],
			["cop_spawn_4","Athira HQ","\a3\ui_f\data\map\GroupIcons\badge_rotate_0_gs.paa"],
			["cop_spawn_5","Air HQ","\a3\ui_f\data\map\Markers\NATO\b_air.paa"],
			["cop_spawn_6","HW Patrol","\a3\ui_f\data\map\GroupIcons\badge_rotate_0_gs.paa"]
		];
	};
	
	case civilian:
	{
		_return = [
			["civ_spawn_2","Kavala","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["civ_spawn_3","Pyrgos","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["civ_spawn_4","Athira","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["civ_spawn_5","Sofia","\a3\ui_f\data\map\MapControl\watertower_ca.paa"]
		];
		
		if(count life_houses > 0) then {
			{
				_pos = call compile format["%1",_x select 0];
				_house = nearestBuilding _pos;
				_houseName = getText(configFile >> "CfgVehicles" >> (typeOf _house) >> "displayName");
				
				_return pushBack [format["house_%1",_house getVariable "uid"],_houseName,"\a3\ui_f\data\map\MapControl\lighthouse_ca.paa"];
			} foreach life_houses;
		};	
	};
	
	case independent: {
		_return = [
			["medic_spawn_2","Kavala Hospital","\a3\ui_f\data\map\MapControl\hospital_ca.paa"],
			["medic_spawn_3","Athira Regional","\a3\ui_f\data\map\MapControl\hospital_ca.paa"],
			["medic_spawn_4","Pygros Hospital","\a3\ui_f\data\map\MapControl\hospital_ca.paa"]
		];
	};
};

_return;

Altis_Life.Altis/core/fn_initCiv.sqf

/*
	File: fn_initCiv.sqf
	Author: Bryan "Tonic" Boardwine

	Description:
	Initializes the civilian.
*/
private["_spawnPos"];
civ_spawn_1 = nearestObjects[getMarkerPos  "civ_spawn_2", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
civ_spawn_2 = nearestObjects[getMarkerPos  "civ_spawn_3", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
civ_spawn_3 = nearestObjects[getMarkerPos  "civ_spawn_4", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
civ_spawn_4 = nearestObjects[getMarkerPos  "civ_spawn_5", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
waitUntil {!(isNull (findDisplay 46))};

if(life_is_arrested) then {
	life_is_arrested = false;
	[player,true] spawn life_fnc_jail;
} else {
	[] call life_fnc_spawnMenu;
	waitUntil{!isNull (findDisplay 38500)}; //Wait for the spawn selection to be open.
	waitUntil{isNull (findDisplay 38500)}; //Wait for the spawn selection to be done.
};
player addRating 9999999;

**Comment by 5RBJS** [comment]
That new version (4.4r1) seems to do the job. I haven't loaded it in the Eden editor yet. I'll let you know if it works when I try to open it in the Eden editor later. Thanks for the help by the way :)

**Comment by Denwo22** [comment]
i cant start the version (4.4r1) on my server ""error loading mission". Debian 8 with @extDB2 and @life_server. i have fixed my own mission.sqm, i can edit with eden and starts on server.

**#INFO: NOT ALL FIXED#**

[mission.zip](https://github.com/TAWTonic/Altis-Life/files/139107/mission.zip)

**Altis_Life.Altis/core/fn_initCiv.sqf**

`/*
	File: fn_initCiv.sqf
	Author: Bryan "Tonic" Boardwine

	Description:
	Initializes the civilian.
*/
private["_spawnPos"];
civ_spawn_2 = nearestObjects[getMarkerPos  "civ_spawn_2", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
civ_spawn_3 = nearestObjects[getMarkerPos  "civ_spawn_3", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
civ_spawn_4 = nearestObjects[getMarkerPos  "civ_spawn_4", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
civ_spawn_5 = nearestObjects[getMarkerPos  "civ_spawn_5", ["Land_i_Shop_01_V1_F","Land_i_Shop_01_V2_F","Land_i_Shop_01_V3_F","Land_i_Shop_02_V1_F","Land_i_Shop_02_V2_F","Land_i_Shop_02_V3_F"],250];
waitUntil {!(isNull (findDisplay 46))};

if(life_is_arrested) then {
	life_is_arrested = false;
	[player,true] spawn life_fnc_jail;
} else {
	[] call life_fnc_spawnMenu;
	waitUntil{!isNull (findDisplay 38500)}; //Wait for the spawn selection to be open.
	waitUntil{isNull (findDisplay 38500)}; //Wait for the spawn selection to be done.
};
player addRating 9999999;`

**Altis_Life.Altis/dialog/function/fn_spawnPointCfg.sqf**

`/*
	File: fn_spawnPointCfg.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master configuration for available spawn points depending on the units side.
	
	Return:
	[Spawn Marker,Spawn Name,Image Path]
*/
private["_side","_return"];
_side = [_this,0,civilian,[civilian]] call BIS_fnc_param;

//Spawn Marker, Spawn Name, PathToImage
switch (_side) do
{
	case west:
	{
		_return = [
			["cop_spawn_2","Kavala HQ","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["cop_spawn_3","Pyrgos HQ","\a3\ui_f\data\map\MapControl\fuelstation_ca.paa"],
			["cop_spawn_4","Athira HQ","\a3\ui_f\data\map\GroupIcons\badge_rotate_0_gs.paa"],
			["cop_spawn_5","Air HQ","\a3\ui_f\data\map\Markers\NATO\b_air.paa"],
			["cop_spawn_6","HW Patrol","\a3\ui_f\data\map\GroupIcons\badge_rotate_0_gs.paa"]
		];
	};
	
	case civilian:
	{
		_return = [
			["civ_spawn_2","Kavala","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["civ_spawn_3","Pyrgos","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["civ_spawn_4","Athira","\a3\ui_f\data\map\MapControl\watertower_ca.paa"],
			["civ_spawn_5","Sofia","\a3\ui_f\data\map\MapControl\watertower_ca.paa"]
		];
		
		if(count life_houses > 0) then {
			{
				_pos = call compile format["%1",_x select 0];
				_house = nearestBuilding _pos;
				_houseName = getText(configFile >> "CfgVehicles" >> (typeOf _house) >> "displayName");
				
				_return pushBack [format["house_%1",_house getVariable "uid"],_houseName,"\a3\ui_f\data\map\MapControl\lighthouse_ca.paa"];
			} foreach life_houses;
		};	
	};
	
	case independent: {
		_return = [
			["medic_spawn_2","Kavala Hospital","\a3\ui_f\data\map\MapControl\hospital_ca.paa"],
			["medic_spawn_3","Athira Regional","\a3\ui_f\data\map\MapControl\hospital_ca.paa"],
			["medic_spawn_4","Pygros Hospital","\a3\ui_f\data\map\MapControl\hospital_ca.paa"]
		];
	};
};

_return;`

**Comment by LegendaryGamingNetwork** [comment]
So im guessing you have made something in EDEN and have tried to load it in the server.

The reason why this does not work is because EDEN uses sqm version 15, while the 2D editor, and the stable version of ArmA 3 uses sqm version 12.

You can try doing this:

Go to eden editor,

Tools> Debug Console: Then type this in: [] call BIS_fnc_3DENExportOldSQM; then do local exec
close that out, go to the mission you want it in, ( save that mission if u havent ) then go to ur mission.sqm in the mission you want it in, go to the bottom, then go up untill you see "class Intro".
Above that line you should see "  }; " add a space above that and paste the sqm that has been copied to your clipboard. Remove all the outros and intros from the text you just put in. 

"
class Intro
{
	addOns[]={};
	addOnsAuto[]={};
	randomSeed=42;
	class Intel
	{
	};
};
class OutroWin
{
	addOns[]={};
	addOnsAuto[]={};
	randomSeed=42;
	class Intel
	{
	};
};
class OutroLoose
{
	addOns[]={};
	addOnsAuto[]={};
	randomSeed=42;
	class Intel
	{
	};
};

"
( make sure you do the ones you just pasted, not the ones that were already in there before you pasted. ) Then go to the top of the text you pasted in and remove:

"
version=12;
class Mission
{
	addOns[]={};
	addOnsAuto[]={};
	randomSeed=42;
	class Intel
	{
	};
	class Groups
	{
		items=0;
	};
"

Then save the file, and reopen the mission in the 2D editor and the objects should be there. And you should be able to put that on a server.

Disclaimer: Untill Eden is fully realesed, this is the only way i know of to do this, but this way only copies the objects, so you would have to play the makers and triggers again in 2D editor. 

P.S. : Sorry if you dont understand something in here, I was typing fast. If you dont, just let me know

**Comment by torchgodz** [comment]
I edit my mission and everything with the 3den editor and everything starts up just fine. One thing i did notice is that the 3den editor puts your mission file in binary code and not plain text. Hope that might help.

**Comment by LegendaryGamingNetwork** [comment]
@torchgodz Lucky you xD every time i make something in eden and copy it over to the altis life file, it doesnt work xD

**Comment by 5RBJS** [comment]
Torch, I think there is an option when you 'Save-As' in the 3DEN editor. There's a tick box at the bottom of the GUI that says something like 'Binarize Mission File'. That should do the job if you untick it. It is ticked by default.

**Comment by danielstuart14** [comment]
nope, that's not the problem...

The problem is that as we have many IDs in our mission, the converting tool from eden mess everything up...

The only way you can solve this, is creating a new mission and pasting the copy/pasting everything from the old mission to the new one. But, when pasting, EDEN changes the markers name, adding +1 to the marker, like that:
```
2d editor:
dealer_1

eden:
dealer_2
```

So, you'll need to rename all the markers, to fix it... I already fixed that in the armalife repo, but we are doing more changes to fix the headless client.
