### ISSUE TITLE
After 1.56 Update

### ISSUE THREAD

**Issue by torchgodz** [TAWTonic/Altis-Life#436]
Is anyone else getting this error after the 1.56 update?
Error in expression <ariable["BIS_fnc_MP_queue",[],TRUE];

{
_x setVariable["sellers",[],true];
} for>
  Error position: <_x setVariable["sellers",[],true];
} for>
  Error Undefined variable in expression: _x
File life_server\init.sqf, line 115
Error in expression <ariable["BIS_fnc_MP_queue",[],TRUE];

{
_x setVariable["sellers",[],true];
} for>
  Error position: <_x setVariable["sellers",[],true];
} for>
  Error Undefined variable in expression: _x
File life_server\init.sqf, line 115
Error in expression <Variable["sellers",[],true];
} foreach [Dealer_1,Dealer_2,Dealer_3];
};
};

[] s>
  Error position: <Dealer_1,Dealer_2,Dealer_3];
};
};

[] s>
  Error Undefined variable in expression: dealer_1
File life_server\init.sqf, line 116

I am unsure if it is hurting anything but im not sure what this does.

**Comment by harmdhast** [comment]
It seams that the "dealer_1" npc was remvoed from your map.

**Comment by torchgodz** [comment]
Hmmm I'll have to look at that cause it's a completely new map form 4.4.
