### ISSUE TITLE
Warning Message: Script \life_server\init.sqf not found

### ISSUE THREAD

**Issue by Levios1** [TAWTonic/Altis-Life#446]
When I try to start my server I get this error:
 Warning Message: Script \life_server\init.sqf not found
Console log:
13:19:01 No speaker given for George Bennett
13:19:01 No speaker given for Shawn Martinez
13:19:01 No speaker given for Joseph Smith
13:19:01 No speaker given for Pan Ng
13:19:01 No speaker given for Kong Il
13:19:01 No speaker given for Oliver Taylor
13:19:01 No speaker given for Thomas Morgan
13:19:01 No speaker given for Harry Faulkner
13:19:01 No speaker given for Kuang Lee
13:19:01 No speaker given for Luke Halliwell
13:19:01 No speaker given for Sean Abbey
13:19:01 No speaker given for Conor Stewart
soldier[B_diver_F]:Some of magazines weren't stored in soldier Vest or Uniform?
13:19:01 No speaker given for Tyler Moore
13:19:01 No speaker given for Davu Tinibu
13:19:01 No speaker given for Keith MacDonald
13:19:01 No speaker given for Geoff Faulkner
13:19:01 No speaker given for Toby Lewis
13:19:01 No speaker given for Charlie Wood
13:19:01 No speaker given for Jack Campbell
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 1c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 2c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 3c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 4c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 5c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 6c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 7c not found
13:19:01 Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 8c not found
13:19:01 Wrong geometry convex component mapping  for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Convex component number 3. not found
13:19:01 No speaker given for Anthis Verga
13:19:01 No speaker given for Achilleas Vidales
13:19:01 No speaker given for Evripidis Mastori
13:19:01 No speaker given for Kostis Kanelloupou
13:19:01 No speaker given for Achilleas Haikias
13:19:01 No speaker given for Dimitiros Savalas
13:19:01 No speaker given for Dimitiros Petridis
13:19:01 No speaker given for Gekas Dimitriadis
13:19:01 No speaker given for Janos Mylonaki
13:19:01 No speaker given for Vangelis Haikias
13:19:01 No speaker given for Giorgos Savalas
13:19:01 No speaker given for Rosi Melidoni
13:19:01 No speaker given for Kostas Kanelloupou
13:19:01 No speaker given for Arion Manetta
13:19:01 No speaker given for Sotiris Baros
13:19:01 No speaker given for Achilleas Xenakis
13:19:01 No speaker given for Lafteris Petridis
13:19:01 No speaker given for Angelos Lagos
13:19:01 No speaker given for Kostas Vidales
13:19:01 No speaker given for Janos Stanis
13:19:01 No speaker given for Kyriakos Isofidou
13:19:01 No speaker given for Vasilis Oikonomopulu
13:19:01 No speaker given for Evripidis Strambopoulos
13:19:02 Strange convex component322 in a3\structures_f\research\dome_big_f.p3d:geometryFire
13:19:02 Strange convex component327 in a3\structures_f\research\dome_big_f.p3d:geometryFire
13:19:03 Mission read.
13:19:03 ../lib/Network/networkServer.cpp OnClientStateChanged:NOT IMPLEMENTED - briefing!
13:19:03 Warning Message: Script \life_server\init.sqf not found
13:20:11  Mission id: e25c2608e6ac3959e9d1fbf822e11660b2ae7055
13:20:11 Game started.
13:20:28 Player [OFM] Felix Global kicked off by BattlEye: Client not responding
13:20:28 Player [OFM] Felix Global disconnected.

I hope you can help me.

**Comment by Levios1** [comment]
I use a linux server

**Comment by Jawshy** [comment]
Do you have [life_server.pbo](https://github.com/TAWTonic/Altis-Life/releases/download/v4.4/life_server.pbo) located in \ARMA_3_DIR\@life_server\addons? 

Does the server's launch command line contain `-mod=@life_server`?

**Comment by Levios1** [comment]
yes

**Comment by danielstuart14** [comment]
arma3server for linux has a buggy -mod parameter.

You can use "-serverMod=" instead, or just copy the life_server.pbo to the folder Addons in the root folder of your arma 3. (Also, copy the extDB2.so + extdb-conf.ini to the root folder)
