### ISSUE TITLE
Setup Correctly, Stuck setting up client

### ISSUE THREAD

**Issue by jonnyetiz** [TAWTonic/Altis-Life#447]
I set everything up properly, and I get Setting Up Client, Please Wait.

RPT Logs: http://pastebin.com/5i6TYxc4

extDB isnt initializing.

Command Line:  -port=2312 "-config=F:\Games\Steam\steamapps\common\Arma 3\TADST\AltisLife\TADST_config.cfg" "-cfg=F:\Games\Steam\steamapps\common\Arma 3\TADST\AltisLife\TADST_basic.cfg" "-profiles=F:\Games\Steam\steamapps\common\Arma 3\TADST\AltisLife" -name=AltisLife -filePatching "-mod=@extDB_Altis;@life_server_altis"

**Comment by danielstuart14** [comment]
you did something wrong. Your mod paths aren't the default ones, so, probably that's the problem.

This is for altis life issues, you should ask support in the forum
