### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by SSnarKW** [TAWTonic/Altis-Life#458]
Sir need to Add SQL it's not Add

i change arma3 to root and when i press GO it's tall me Error i'm been Freeze about three Days Help
Look SQL if was Error Or What Help me PLZ

**Comment by SSnarKW** [comment]
That Error =======> Link:-  https://paste.ee/p/fnslj

**Comment by kampfbonn** [comment]
Select a Database is an Option...
